### ISSUE TITLE
Kong Example

### ISSUE THREAD

**Issue by vinckr** [ory/works#16]
**Is your feature request related to a problem? Please describe.**

There is no example for Kong. 

**Describe the solution you'd like**

An example for Kong. It needs to be clarified what exactly that entails

**Describe alternatives you've considered**

If you want to use Kong I don't see an alternative, but please point out if there are.

**Comment by vinckr** [comment]
@githugt
You want to collaborate with us on this?

**Comment by vinckr** [comment]
stale

**Comment by githugt** [comment]
I actually did manage to create a small blog on exactly this. I didn't get time to review those bits though. But then later got into a few big projects. 
I'll connect with you on slack by next week??

**Comment by vinckr** [comment]
Hey @githugt,
cool that sounds great! 
Please do reach out to me on Slack. We might even get it published on https://www.ory.sh/blog/ if you would like that.
